server:
  port: 8401
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        recommend:
          timer:
            recall: true
            profile: true
            predict: true
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 60000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 60000 #服务请求处理超时时间（毫秒）
