spring:
  datasource:
    url: jdbc:mysql://192.168.1.111:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: 192.168.1.111