apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-auth-deployment
  namespace: default
  labels:
    app: mall-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-auth
  template:
    metadata:
      labels:
        app: mall-auth
    spec:
      containers:
        - name: mall-auth
          # 指定Docker Hub中的镜像地址
          image: 192.168.1.100:5000/mall-auth:2.0-SNAPSHOT
          ports:
            - containerPort: 8401
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            # 指定Nacos地址
            - name: spring.cloud.nacos.discovery.server-addr
              value: http://192.168.1.238:8848
            - name: spring.cloud.nacos.config.server-addr
              value: http://192.168.1.238:8848
          volumeMounts:
            - mountPath: /var/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mydata/app/mall-auth/logs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mall-admin-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mall-admin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080